global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: buildpiper-impl
    env: test

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:

  - job_name: 'blackbox-tcp-buildpiper'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
          - host.docker.internal:3306
          - host.docker.internal:6379
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'blackbox-http-buildpiper'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://host.docker.internal:9125/health
        labels:
          name: "bp-agent"
      - targets:
          - http://host.docker.internal:9124/health
        labels:
          name: "deploy-api"
      - targets:
          - http://host.docker.internal:9123/health
        labels:
          name: "scheduled-api"
      - targets:
          - http://host.docker.internal:80/health
        labels:
          name: "frontend"
      - targets:
          - http://host.docker.internal:9001/health
        labels:
          name: "public-api"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'mysql'
    static_configs:
      - targets: ['db-exporter:9104']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']